export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>Proyecto</title>
  <base href="https://diegocaspe.github.io/practica4/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="footer.css">
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:Arial,Helvetica,sans-serif;background-color:#0ff;color:#006400;padding:10px}
</style><link rel="stylesheet" href="styles-J5VKUGND.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-J5VKUGND.css"></noscript><style ng-app-id="ng">header[_ngcontent-ng-c2446980934]{background-color:#000;padding:10px}nav[_ngcontent-ng-c2446980934]   a[_ngcontent-ng-c2446980934]{color:#fff;margin:0 15px;text-decoration:none;padding:10px 20px}nav[_ngcontent-ng-c2446980934]   a[_ngcontent-ng-c2446980934]:hover{background-color:#fff;color:#000;border-radius:15px}</style><style ng-app-id="ng">footer[_ngcontent-ng-c2361652235]{background-color:#333;color:#fff;text-align:center;padding:20px 0;font-size:16px}footer[_ngcontent-ng-c2361652235]   p[_ngcontent-ng-c2361652235]{margin:0;font-weight:300}footer[_ngcontent-ng-c2361652235]   a[_ngcontent-ng-c2361652235]{color:#fff;text-decoration:none}footer[_ngcontent-ng-c2361652235]   a[_ngcontent-ng-c2361652235]:hover{text-decoration:underline}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="20.3.9" ngh="1" ng-server-context="ssg"><app-header _nghost-ng-c2446980934 ngh="0"><header _ngcontent-ng-c2446980934><nav _ngcontent-ng-c2446980934><a _ngcontent-ng-c2446980934 routerlink="/" href="https://diegocaspe.github.io/practica4/" jsaction="click:;">Inicio</a><a _ngcontent-ng-c2446980934 routerlink="/nosotros" href="https://diegocaspe.github.io/practica4/nosotros" jsaction="click:;">Nosotros</a><a _ngcontent-ng-c2446980934 routerlink="/productos" href="https://diegocaspe.github.io/practica4/productos" jsaction="click:;">Productos</a><a _ngcontent-ng-c2446980934 routerlink="/contacto" href="https://diegocaspe.github.io/practica4/contacto" jsaction="click:;">Contacto</a></nav></header></app-header><main><router-outlet></router-outlet><app-contact ngh="0"><p>contact works!</p></app-contact><!----></main><app-footer _nghost-ng-c2361652235 ngh="0"><footer _ngcontent-ng-c2361652235 class="bg-dark text-white text-center py-3"><p _ngcontent-ng-c2361652235>© 2025 Mi Proyecto - Todos los derechos reservados.</p><ul _ngcontent-ng-c2361652235 class="list-unstyled"><li _ngcontent-ng-c2361652235><a _ngcontent-ng-c2361652235 href="/about" class="text-white">Acerca de</a></li><li _ngcontent-ng-c2361652235><a _ngcontent-ng-c2361652235 href="/contact" class="text-white">Contacto</a></li><li _ngcontent-ng-c2361652235><a _ngcontent-ng-c2361652235 href="/products" class="text-white">Productos</a></li></ul></footer></app-footer></app-root>
<script src="polyfills-5CFQRCPP.js" type="module"></script><script src="main-AEV3D7FV.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"2":[{"i":"c1931389011","r":1}]}}]}</script></body></html>`;